<h1>Coffee Trends</h1>

In [112]:
import pandas as pd
from ydata_profiling import ProfileReport

In [113]:
coffeePriceTrends = pd.read_excel("../Datasets/Price_Trend_1992_93_2015_USD.xls")

In [114]:
coffeePriceTrends = coffeePriceTrends.drop(['Unnamed: 0', 'Unnamed: 9'],
                      axis=1,
                      )

In [115]:
coffeePriceTrends

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,AVERAGE PRICES PAID TO FARMERS AND PROCESSORS ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DEC 2013 IN UGANDA SHILLINGS PER KILOGRAM (U ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Shs,NaN,NaN,NaN,$,NaN,NaN
3,MONTH,ROBUSTA KIBOKO,ROBUSTA FAQ,ARABICA PARCHMENT,EX.RATE Sh/Kg,ROBUSTA KIBOKO,ROBUSTA FAQ,ARABICA PARCHMENT
4,1992-07-01 00:00:00,210,420,499,1177.86,0.178289,0.356579,0.42365
...,...,...,...,...,...,...,...,...
280,2015-07-01 00:00:00,2200,4350,5850,3360.09,0.654744,1.294608,1.741025
281,2015-08-01 00:00:00,2200,4500,6250,3548.25,0.620024,1.268231,1.761432
282,2015-09-01 00:00:00,2150,4250,5750,3667.5,0.58623,1.158828,1.567825
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,Source: UCDA Database,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
columnNames = coffeePriceTrends.loc[3].tolist()

In [117]:
columnNames

['MONTH',
 'ROBUSTA KIBOKO',
 'ROBUSTA FAQ',
 'ARABICA PARCHMENT',
 'EX.RATE Sh/Kg',
 'ROBUSTA KIBOKO',
 'ROBUSTA FAQ',
 'ARABICA PARCHMENT']

In [118]:
coffeePriceTrends.drop(coffeePriceTrends.index[:4], inplace=True,
                       axis=0,
                      )

In [119]:
coffeePriceTrends

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
4,1992-07-01 00:00:00,210,420,499,1177.86,0.178289,0.356579,0.42365
5,1992-08-01 00:00:00,220,440,500,1185.29,0.185609,0.371217,0.421838
6,1992-09-01 00:00:00,215,400,502,1185.15,0.181412,0.33751,0.423575
7,1992-10-01 00:00:00,225,450,510,1181.07,0.190505,0.38101,0.431812
8,1992-11-01 00:00:00,250,500,550,1196.34,0.208971,0.417941,0.459736
...,...,...,...,...,...,...,...,...
280,2015-07-01 00:00:00,2200,4350,5850,3360.09,0.654744,1.294608,1.741025
281,2015-08-01 00:00:00,2200,4500,6250,3548.25,0.620024,1.268231,1.761432
282,2015-09-01 00:00:00,2150,4250,5750,3667.5,0.58623,1.158828,1.567825
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,Source: UCDA Database,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
oldColumnNames = coffeePriceTrends.columns.tolist()

In [121]:
oldColumnNames

['Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8']

In [122]:
{oldColumnNames[x]:columnNames[x] for x in range(len(columnNames))}

{'Unnamed: 1': 'MONTH',
 'Unnamed: 2': 'ROBUSTA KIBOKO',
 'Unnamed: 3': 'ROBUSTA FAQ',
 'Unnamed: 4': 'ARABICA PARCHMENT',
 'Unnamed: 5': 'EX.RATE Sh/Kg',
 'Unnamed: 6': 'ROBUSTA KIBOKO',
 'Unnamed: 7': 'ROBUSTA FAQ',
 'Unnamed: 8': 'ARABICA PARCHMENT'}

In [123]:
columnNames

['MONTH',
 'ROBUSTA KIBOKO',
 'ROBUSTA FAQ',
 'ARABICA PARCHMENT',
 'EX.RATE Sh/Kg',
 'ROBUSTA KIBOKO',
 'ROBUSTA FAQ',
 'ARABICA PARCHMENT']

In [124]:
coffeePriceTrends = coffeePriceTrends.rename(columns={oldColumnNames[x]:columnNames[x] for x in range(len(columnNames))})

In [125]:
coffeePriceTrends = coffeePriceTrends.set_index('MONTH')

In [126]:
coffeePriceTrends

,ROBUSTA KIBOKO,ROBUSTA FAQ,ARABICA PARCHMENT,EX.RATE Sh/Kg,ROBUSTA KIBOKO,ROBUSTA FAQ,ARABICA PARCHMENT
MONTH,,,,,,,
1992-07-01 00:00:00,210,420,499,1177.86,0.178289,0.356579,0.42365
1992-08-01 00:00:00,220,440,500,1185.29,0.185609,0.371217,0.421838
1992-09-01 00:00:00,215,400,502,1185.15,0.181412,0.33751,0.423575
1992-10-01 00:00:00,225,450,510,1181.07,0.190505,0.38101,0.431812
1992-11-01 00:00:00,250,500,550,1196.34,0.208971,0.417941,0.459736
...,...,...,...,...,...,...,...
2015-07-01 00:00:00,2200,4350,5850,3360.09,0.654744,1.294608,1.741025
2015-08-01 00:00:00,2200,4500,6250,3548.25,0.620024,1.268231,1.761432
2015-09-01 00:00:00,2150,4250,5750,3667.5,0.58623,1.158828,1.567825
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Source: UCDA Database,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
index = pd.MultiIndex.from_arrays([["UGX", "UGX", "UGX", "EX.RATE", "USD", "USD", "USD"],
                                   ["ROBUSTA KIBOKO", "ROBUSTA FAQ", "ARABICA PARCHMENT", "EX.RATE Sh/Kg", "ROBUSTA KIBOKO", "ROBUSTA FAQ", "ARABICA PARCHMENT"]])

In [128]:
coffeePriceTrends.columns = index

In [129]:
coffeePriceTrends

                                 UGX                                \
                      ROBUSTA KIBOKO ROBUSTA FAQ ARABICA PARCHMENT
MONTH
1992-07-01 00:00:00              210         420               499
1992-08-01 00:00:00              220         440               500
1992-09-01 00:00:00              215         400               502
1992-10-01 00:00:00              225         450               510
1992-11-01 00:00:00              250         500               550
...                              ...         ...               ...
2015-07-01 00:00:00             2200        4350              5850
2015-08-01 00:00:00             2200        4500              6250
2015-09-01 00:00:00             2150        4250              5750
NaN                              NaN         NaN               NaN
Source: UCDA Database            NaN         NaN               NaN

                            EX.RATE            USD              \
                      EX.RATE Sh/Kg ROBUSTA KIBOKO ROBUSTA FAQ
MONTH
1992-07-01 00:00:00         1177.86       0.178289    0.356579
1992-08-01 00:00:00         1185.29       0.185609    0.371217
1992-09-01 00:00:00         1185.15       0.181412     0.33751
1992-10-01 00:00:00         1181.07       0.190505     0.38101
1992-11-01 00:00:00         1196.34       0.208971    0.417941
...                             ...            ...         ...
2015-07-01 00:00:00         3360.09       0.654744    1.294608
2015-08-01 00:00:00         3548.25       0.620024    1.268231
2015-09-01 00:00:00          3667.5        0.58623    1.158828
NaN                             NaN            NaN         NaN
Source: UCDA Database           NaN            NaN         NaN


                      ARABICA PARCHMENT
MONTH
1992-07-01 00:00:00             0.42365
1992-08-01 00:00:00            0.421838
1992-09-01 00:00:00            0.423575
1992-10-01 00:00:00            0.431812
1992-11-01 00:00:00            0.459736
...                                 ...
2015-07-01 00:00:00            1.741025
2015-08-01 00:00:00            1.761432
2015-09-01 00:00:00            1.567825
NaN                                 NaN
Source: UCDA Database               NaN

[281 rows x 7 columns]

In [130]:
# stats = []
# for cl in coffeePriceTrends.columns:
#     stats.append((cl,
#                   coffeePriceTrends[cl].nunique(),
#                   coffeePriceTrends[cl].isnull().sum(),
#                   coffeePriceTrends[cl].isnull().sum() * 100 / coffeePriceTrends.shape[0],
#                   coffeePriceTrends[cl].value_counts(normalize=True, dropna=False).values[0] * 100,
#                   coffeePriceTrends[cl].dtype))
# stats_df = pd.DataFrame(stats, columns=['Feature',
#                                         'Unique Values',
#                                         'Missing Values',
#                                         'Missing Values [%]',
#                                         'Values in the biggest category [%]',
#                                         'Datatype'])
# stats_df.sort_values('Missing Values [%]', ascending=False)

In [131]:
# ProfileReport(coffeePriceTrends,
#                                 title="Coffee",
#                             )

DispatchError: Function <code object pandas_preprocess at 0x0000022C905ECA50, file "D:\PyData Kampala\PyDataCurriculum\PyDataVenv\Lib\site-packages\ydata_profiling\model\pandas\dataframe_pandas.py", line 16>